### ISSUE TITLE
Cache Creation and Access Errors on Windows 11 - Electron App

### ISSUE THREAD

**Issue by XDoumsg** [mycrl/hylarana#32]
I'm encountering an issue when running the `mirror.exe` file on Windows 11. The application seems to fail when attempting to create and access the GPU cache, resulting in multiple errors. Below are the error messages I receive in the PowerShell terminal:

```shell
PS D:\Users\Doumsg\Downloads\windows-x64-app-release\bin> ./mirror.exe
PS D:\Users\Doumsg\Downloads\windows-x64-app-release\bin>
[4208:0812/131423.592:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[4208:0812/131423.592:ERROR:disk_cache.cc(208)] Unable to create cache
[4208:0812/131423.602:ERROR:gpu_disk_cache.cc(711)] Gpu Cache Creation failed: -2
[3612:0812/131423.640:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
-> ELECTRON: [info] - ipc update settings event
-> ELECTRON: [info] - rebuild mirror env
-> ELECTRON: [error] - Error: mirror create failed
-> ELECTRON: [info] - ipc get devices event
```

**Steps to Reproduce:**
1. Download the `windows-x64-app-release` package.
2. Navigate to the `bin` directory using PowerShell.
3. Run the `mirror.exe` file.

**Expected Behavior:**
The application should run without errors, and the necessary caches should be created and accessed successfully.

**Actual Behavior:**
The application fails to create and access the GPU cache, leading to several errors indicating "Access Denied" and "Cache Creation failed."

**Environment:**
- OS: Windows 11
- Version: [Include your version of Windows and any relevant software versions]
- Electron Version: [Include the version of Electron, if applicable]

**Additional Information:**
The error code `0x5` suggests that there might be a permissions issue preventing the application from accessing or creating the cache. However, running PowerShell as an administrator did not resolve the problem.

**Comment by mycrl** [comment]
I'm surprised that anyone actually started using this project. I need to inform everyone that this project is still under development and will often make some breaking updates, but I will launch a usable version as soon as possible.

It should be noted that the entire project needs more updates and fixes, so I haven't written a how-to document yet.

First you need to run mirror-service. If this file is not in the app package, you can find it in the non-app package, which can be obtained in releases, and then run mirror-service.

Then you run mirror.exe. If the taskbar icon appears normally, it is normal. You need to enter the settings interface (a small gear), set the server address (mirror-service binding address), and make other settings you think are necessary, and then close the settings page. After closing the settings page, your settings will be updated. At this time, you should be able to select the capture device on the interface and start casting. Of course, the receiving end is the same process, but the receiving end does not need to select the capture device.

It should be noted that the receiving end and the sending end need to use the same channel id.

**Comment by mycrl** [comment]
Then I will update, cef cannot access the cache is not a problem, it should not affect the use, you can ignore this problem.

The 0.0.4 stable version is only stable for the SDK. The electron app was not originally a part of the project. This is a new implementation that I decided to add on a whim to show how the SDK is integrated in electron, and it can also help me find some possible problems.
