### ISSUE TITLE
rust example compile failed

### ISSUE THREAD

**Issue by wzzc-dev** [mycrl/hylarana#56]
Failed to compile on the riscv machine

rust version：rustc 1.82.0 (f6e511eec 2024-10-15)

log：

cargo run -- --width=1920 --height=1080 --fps=30 --encoder=libx264 --decoder=h264 --address=127.0.0.1:8080 --strategy=relay
   Compiling hylarana-codec v0.2.0-beta.1 (/home/chuang/hylarana-0.2.0-beta.7/codec)
   Compiling colored v2.1.0
   Compiling percent-encoding v2.3.1
   Compiling smol_str v0.2.2
error[E0412]: cannot find type `__va_list_tag` in this scope
  --> codec/src/lib.rs:54:21
   |
54 | type va_list = *mut __va_list_tag;
   |                     ^^^^^^^^^^^^^ not found in this scope

   Compiling dpi v0.1.1
For more information about this error, try `rustc --explain E0412`.
error: could not compile `hylarana-codec` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

**Comment by mycrl** [comment]
Can you show what the function signature of the `av_log_set_callback` function looks like on your device? I use this function at `codec/src/lib.rs:108` location.

**Comment by wzzc-dev** [comment]
Sorry I'm late. Is that what you wanted to see?

 ![image](https://github.com/user-attachments/assets/9ed97c75-a6c4-4886-a66a-b1ec70c7f696)
```shell
$ grep -r "av_log_set_callback" /usr/include/ffmpeg/
/usr/include/ffmpeg/libavutil/log.h: * @see av_log_set_callback
/usr/include/ffmpeg/libavutil/log.h: * @see av_log_set_callback
/usr/include/ffmpeg/libavutil/log.h:void av_log_set_callback(void (*callback)(void*, int, const char*, va_list));
```

**Comment by mycrl** [comment]
It's okay.

What I meant was what kind of function signature this function has in rust.
Since I don't have a riscv device and the code for rust is generated by bindgen from ffmpeg's header file, I don't know what the `av_log_set_callback` generated by bindgen looks like on a riscv.
So you need to go to a bit of trouble on your end and use a quick preview like ide or a similar mechanism to see what the rust signature of this function looks like.
Or I'll figure out how to emulate the riscv environment with qemu.

**Comment by wzzc-dev** [comment]
Can you give me some guidance? The performance of riscv device is relatively low. ide cannot be used on it. Is there any command to check the signature you mentioned

**Comment by mycrl** [comment]
fix for: https://github.com/mycrl/hylarana/commit/95f5d09fa9c73228ad372ea003e27edb748f4918

But since my project depends on ffmpeg, is there currently a riscv branch for ffmpeg? I'm not quite sure. So this project is still not working on riscv at the moment.
